# Generated by Django 4.0.5 on 2022-06-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Libro')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Maceteros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.PositiveSmallIntegerField(choices=[(1, '5cm'), (2, '10cm'), (3, '15cm'), (4, '20cm'), (5, '25cm'), (6, '30cm')], verbose_name='Tamaño')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Plastico'), (2, 'Madera'), (3, 'Cemento')], verbose_name='Tipo')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('precio', models.FloatField(max_length=10, verbose_name='Precio')),
                ('lugar', models.PositiveSmallIntegerField(choices=[(1, 'Interior'), (2, 'Exterior'), (3, 'Interior/Exterior')], verbose_name='Espacio')),
            ],
        ),
    ]
