# Generated by Django 4.0.5 on 2022-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='Usuario')),
                ('email', models.CharField(max_length=100, verbose_name='Mail')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='libros',
            name='precio',
            field=models.FloatField(verbose_name='Precio $'),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='precio',
            field=models.FloatField(verbose_name='Precio $'),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='precio',
            field=models.FloatField(max_length=10, verbose_name='Precio $'),
        ),
    ]
