# Generated by Django 4.0.5 on 2022-07-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_usuario_alter_libros_precio_alter_maceteros_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('precio', models.FloatField(max_length=10, verbose_name='Precio $')),
            ],
        ),
        migrations.RemoveField(
            model_name='maceteros',
            name='tamaño',
        ),
    ]
