# Generated by Django 4.0.5 on 2022-07-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_inventario_remove_maceteros_tamaño'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libros',
        ),
        migrations.DeleteModel(
            name='Maceteros',
        ),
        migrations.DeleteModel(
            name='Plantas',
        ),
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(default='algo', max_length=200, upload_to=''),
        ),
    ]
